"""init EAV

Revision ID: 0b176b23d7c9
Revises: 4b368ffec557
Create Date: 2024-07-24 21:59:49.547249

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0b176b23d7c9'
down_revision: Union[str, None] = '4b368ffec557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributedefinition',
    sa.Column('attr_sys_id', sa.Integer(), nullable=False),
    sa.Column('attr_name', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('attr_sys_id')
    )
    op.create_index(op.f('ix_attributedefinition_attr_name'), 'attributedefinition', ['attr_name'], unique=False)
    op.create_index(op.f('ix_attributedefinition_attr_sys_id'), 'attributedefinition', ['attr_sys_id'], unique=False)
    op.create_table('stringattribute',
    sa.Column('str_attr_sys_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('attr_sys_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('value_code', sa.String(), nullable=True),
    sa.Column('parent_str_attr_sys_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attr_sys_id'], ['attributedefinition.attr_sys_id'], ),
    sa.ForeignKeyConstraint(['parent_str_attr_sys_id'], ['stringattribute.str_attr_sys_id'], ),
    sa.PrimaryKeyConstraint('str_attr_sys_id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'attr_sys_id', 'value', 'parent_str_attr_sys_id')
    )
    op.create_index(op.f('ix_stringattribute_str_attr_sys_id'), 'stringattribute', ['str_attr_sys_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stringattribute_str_attr_sys_id'), table_name='stringattribute')
    op.drop_table('stringattribute')
    op.drop_index(op.f('ix_attributedefinition_attr_sys_id'), table_name='attributedefinition')
    op.drop_index(op.f('ix_attributedefinition_attr_name'), table_name='attributedefinition')
    op.drop_table('attributedefinition')
    # ### end Alembic commands ###
