"""hypothecation fields

Revision ID: 157f679f4a7e
Revises: 560487036ed1
Create Date: 2024-10-27 21:01:03.269449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157f679f4a7e'
down_revision: Union[str, None] = '560487036ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('prop_bank_cust_code', sa.String(), nullable=True))
    op.add_column('proposal', sa.Column('prop_bank_cust_name', sa.String(), nullable=True))
    op.add_column('proposal', sa.Column('pol_hypothecation_yn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'pol_hypothecation_yn')
    op.drop_column('proposal', 'prop_bank_cust_name')
    op.drop_column('proposal', 'prop_bank_cust_code')
    # ### end Alembic commands ###
