"""hypothecation json field

Revision ID: 1ead85db9edd
Revises: 4a0553b719eb
Create Date: 2024-10-29 13:52:05.391683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ead85db9edd'
down_revision: Union[str, None] = '4a0553b719eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('prop_hypothecation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'prop_hypothecation')
    # ### end Alembic commands ###
