"""update payload_out

Revision ID: 340fe63506f8
Revises: 1ead85db9edd
Create Date: 2025-01-25 12:14:38.933038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '340fe63506f8'
down_revision: Union[str, None] = '1ead85db9edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('externalpayload', sa.Column('payload_out', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('externalpayload', 'payload_out')
    # ### end Alembic commands ###
