"""init

Revision ID: 448cbfd0daac
Revises:
Create Date: 2024-05-26 22:39:59.978039

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "448cbfd0daac"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payload",
        sa.Column("pl_sys_id", sa.Integer(), nullable=False),
        sa.Column("MCINotification", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("pl_sys_id"),
    )
    op.create_index(
        op.f("ix_payload_MCINotification"), "payload", ["MCINotification"], unique=False
    )
    op.create_index(
        op.f("ix_payload_pl_sys_id"), "payload", ["pl_sys_id"], unique=False
    )
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_person_email"), "person", ["email"], unique=True)
    op.create_index(op.f("ix_person_full_name"), "person", ["full_name"], unique=False)
    op.create_index(op.f("ix_person_id"), "person", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("nic", sa.String(), nullable=True),
        sa.Column("pin", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("dob", sa.DateTime(), nullable=True),
        sa.Column("agent_code", sa.String(length=10), nullable=True),
        sa.Column("agency_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_staff", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("staff_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["person.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_description"), "item", ["description"], unique=False)
    op.create_index(op.f("ix_item_id"), "item", ["id"], unique=False)
    op.create_index(op.f("ix_item_title"), "item", ["title"], unique=False)
    op.create_table(
        "quote",
        sa.Column("quot_sys_id", sa.Integer(), nullable=False),
        sa.Column("quot_ref", sa.String(), nullable=False),
        sa.Column("quot_paymt_ref", sa.String(), nullable=True),
        sa.Column("quot_paymt_date", sa.DateTime(), nullable=True),
        sa.Column("quot_assr_name", sa.String(), nullable=True),
        sa.Column("quot_assr_nic", sa.String(), nullable=True),
        sa.Column("quot_assr_pin", sa.String(), nullable=True),
        sa.Column("quot_assr_phone", sa.String(), nullable=True),
        sa.Column("quot_assr_email", sa.String(), nullable=True),
        sa.Column(
            "quot_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("quot_assr_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["quot_assr_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("quot_sys_id"),
    )
    op.create_index(op.f("ix_quote_quot_ref"), "quote", ["quot_ref"], unique=False)
    op.create_index(
        op.f("ix_quote_quot_sys_id"), "quote", ["quot_sys_id"], unique=False
    )
    op.create_table(
        "proposal",
        sa.Column("prop_sys_id", sa.Integer(), nullable=False),
        sa.Column("prop_sr_no", sa.Integer(), nullable=False),
        sa.Column("prop_paymt_ref", sa.String(), nullable=True),
        sa.Column("prop_paymt_date", sa.DateTime(), nullable=True),
        sa.Column("pol_quot_sys_id", sa.Integer(), nullable=True),
        sa.Column("pol_quot_no", sa.String(), nullable=True),
        sa.Column("pol_comp_code", sa.String(), nullable=False),
        sa.Column("pol_divn_code", sa.String(), nullable=False),
        sa.Column("pol_dept_code", sa.String(), nullable=True),
        sa.Column("pol_prod_code", sa.String(), nullable=False),
        sa.Column("pol_type", sa.String(), nullable=False),
        sa.Column("pol_cust_code", sa.String(), nullable=False),
        sa.Column("pol_assr_code", sa.String(), nullable=True),
        sa.Column("pol_fm_dt", sa.DateTime(), nullable=False),
        sa.Column("pol_to_dt", sa.DateTime(), nullable=False),
        sa.Column("pol_dflt_si_curr_code", sa.String(), nullable=False),
        sa.Column("pol_prem_curr_code", sa.String(), nullable=False),
        sa.Column("pol_flexi", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pol_sys_id", sa.Integer(), nullable=True),
        sa.Column("pol_end_no_idx", sa.Integer(), nullable=True),
        sa.Column("pol_no", sa.String(), nullable=True),
        sa.Column("pol_cr_dt", sa.DateTime(), nullable=True),
        sa.Column("pol_appr_dt", sa.DateTime(), nullable=True),
        sa.Column("pol_sts", sa.String(), nullable=True),
        sa.Column("prop_quot_sys_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prop_quot_sys_id"],
            ["quote.quot_sys_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("prop_sys_id"),
    )
    op.create_index(
        op.f("ix_proposal_prop_sys_id"), "proposal", ["prop_sys_id"], unique=False
    )
    op.create_table(
        "proposalcharge",
        sa.Column("chg_sys_id", sa.Integer(), nullable=False),
        sa.Column("chg_sr_no", sa.Integer(), nullable=False),
        sa.Column("pchg_code", sa.String(), nullable=False),
        sa.Column("pchg_type", sa.String(), nullable=False),
        sa.Column("pchg_perc", sa.Float(), nullable=True),
        sa.Column("pchg_chg_fc", sa.Float(), nullable=True),
        sa.Column("pchg_prem_curr_code", sa.String(), nullable=False),
        sa.Column("pchg_rate_per", sa.Float(), nullable=True),
        sa.Column("pchg_flexi", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pchg_sys_id", sa.Integer(), nullable=True),
        sa.Column("pchg_pol_sys_id", sa.Integer(), nullable=True),
        sa.Column("pchg_end_no_idx", sa.Integer(), nullable=True),
        sa.Column("chg_prop_sys_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chg_prop_sys_id"],
            ["proposal.prop_sys_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chg_sys_id"),
    )
    op.create_index(
        op.f("ix_proposalcharge_chg_sys_id"),
        "proposalcharge",
        ["chg_sys_id"],
        unique=False,
    )
    op.create_table(
        "proposalsection",
        sa.Column("sec_sys_id", sa.Integer(), nullable=False),
        sa.Column("sec_sr_no", sa.Integer(), nullable=False),
        sa.Column("psec_sec_code", sa.String(), nullable=False),
        sa.Column("psec_flexi", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("psec_sys_id", sa.Integer(), nullable=True),
        sa.Column("psec_pol_sys_id", sa.Integer(), nullable=True),
        sa.Column("psec_end_no_idx", sa.Integer(), nullable=True),
        sa.Column("sec_prop_sys_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sec_prop_sys_id"],
            ["proposal.prop_sys_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sec_sys_id"),
    )
    op.create_index(
        op.f("ix_proposalsection_sec_sys_id"),
        "proposalsection",
        ["sec_sys_id"],
        unique=False,
    )
    op.create_table(
        "proposalrisk",
        sa.Column("risk_sys_id", sa.Integer(), nullable=False),
        sa.Column("risk_sr_no", sa.Integer(), nullable=False),
        sa.Column("prai_data_18", sa.String(), nullable=True),
        sa.Column("prai_code_03", sa.String(), nullable=True),
        sa.Column("prai_desc_09", sa.String(), nullable=True),
        sa.Column("prai_flexi", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prai_sys_id", sa.Integer(), nullable=True),
        sa.Column("prai_risk_lvl_no", sa.Integer(), nullable=True),
        sa.Column("prai_risk_id", sa.Integer(), nullable=True),
        sa.Column("prai_pol_sys_id", sa.Integer(), nullable=True),
        sa.Column("prai_end_no_idx", sa.Integer(), nullable=True),
        sa.Column("risk_sec_sys_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["risk_sec_sys_id"],
            ["proposalsection.sec_sys_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("risk_sys_id"),
    )
    op.create_index(
        op.f("ix_proposalrisk_risk_sys_id"),
        "proposalrisk",
        ["risk_sys_id"],
        unique=False,
    )
    op.create_table(
        "proposalcover",
        sa.Column("cvr_sys_id", sa.Integer(), nullable=False),
        sa.Column("cvr_sr_no", sa.Integer(), nullable=False),
        sa.Column("prc_code", sa.String(), nullable=False),
        sa.Column("prc_rate", sa.Float(), nullable=True),
        sa.Column("prc_rate_per", sa.Float(), nullable=True),
        sa.Column("prc_si_curr_code", sa.String(), nullable=False),
        sa.Column("prc_prem_curr_code", sa.String(), nullable=False),
        sa.Column("prc_si_fc", sa.Float(), nullable=True),
        sa.Column("prc_prem_fc", sa.Float(), nullable=True),
        sa.Column("prc_flexi", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prc_sys_id", sa.Integer(), nullable=True),
        sa.Column("prc_sr_no", sa.Integer(), nullable=True),
        sa.Column("prc_lvl1_sys_id", sa.Integer(), nullable=True),
        sa.Column("prc_pol_sys_id", sa.Integer(), nullable=True),
        sa.Column("prc_end_no_idx", sa.Integer(), nullable=True),
        sa.Column("cvr_risk_sys_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cvr_risk_sys_id"],
            ["proposalrisk.risk_sys_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("cvr_sys_id"),
    )
    op.create_index(
        op.f("ix_proposalcover_cvr_sys_id"),
        "proposalcover",
        ["cvr_sys_id"],
        unique=False,
    )
    op.create_table(
        "proposalsmi",
        sa.Column("smi_sys_id", sa.Integer(), nullable=False),
        sa.Column("smi_sr_no", sa.Integer(), nullable=False),
        sa.Column("prs_smi_code", sa.String(), nullable=False),
        sa.Column("prs_rate", sa.Float(), nullable=True),
        sa.Column("prs_rate_per", sa.Float(), nullable=True),
        sa.Column("prs_si_fc", sa.Float(), nullable=True),
        sa.Column("prs_prem_fc", sa.Float(), nullable=True),
        sa.Column("prs_smi_desc", sa.String(), nullable=True),
        sa.Column("prs_flexi", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prs_sys_id", sa.Integer(), nullable=True),
        sa.Column("prs_lvl1_sys_id", sa.Integer(), nullable=True),
        sa.Column("prs_pol_sys_id", sa.Integer(), nullable=True),
        sa.Column("prs_end_no_idx", sa.Integer(), nullable=True),
        sa.Column("prs_psec_sys_id", sa.Integer(), nullable=True),
        sa.Column("smi_risk_sys_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["smi_risk_sys_id"],
            ["proposalrisk.risk_sys_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("smi_sys_id"),
    )
    op.create_index(
        op.f("ix_proposalsmi_smi_sys_id"), "proposalsmi", ["smi_sys_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proposalsmi_smi_sys_id"), table_name="proposalsmi")
    op.drop_table("proposalsmi")
    op.drop_index(op.f("ix_proposalcover_cvr_sys_id"), table_name="proposalcover")
    op.drop_table("proposalcover")
    op.drop_index(op.f("ix_proposalrisk_risk_sys_id"), table_name="proposalrisk")
    op.drop_table("proposalrisk")
    op.drop_index(op.f("ix_proposalsection_sec_sys_id"), table_name="proposalsection")
    op.drop_table("proposalsection")
    op.drop_index(op.f("ix_proposalcharge_chg_sys_id"), table_name="proposalcharge")
    op.drop_table("proposalcharge")
    op.drop_index(op.f("ix_proposal_prop_sys_id"), table_name="proposal")
    op.drop_table("proposal")
    op.drop_index(op.f("ix_quote_quot_sys_id"), table_name="quote")
    op.drop_index(op.f("ix_quote_quot_ref"), table_name="quote")
    op.drop_table("quote")
    op.drop_index(op.f("ix_item_title"), table_name="item")
    op.drop_index(op.f("ix_item_id"), table_name="item")
    op.drop_index(op.f("ix_item_description"), table_name="item")
    op.drop_table("item")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_person_id"), table_name="person")
    op.drop_index(op.f("ix_person_full_name"), table_name="person")
    op.drop_index(op.f("ix_person_email"), table_name="person")
    op.drop_table("person")
    op.drop_index(op.f("ix_payload_pl_sys_id"), table_name="payload")
    op.drop_index(op.f("ix_payload_MCINotification"), table_name="payload")
    op.drop_table("payload")
    # ### end Alembic commands ###
