"""Licence COI Number

Revision ID: 4a0553b719eb
Revises: 157f679f4a7e
Create Date: 2024-10-29 12:16:33.871882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0553b719eb'
down_revision: Union[str, None] = '157f679f4a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('quot_assr_lic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'quot_assr_lic')
    # ### end Alembic commands ###
