"""init masters

Revision ID: 4b368ffec557
Revises: 53f90d9a3631
Create Date: 2024-07-22 14:57:53.306164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b368ffec557'
down_revision: Union[str, None] = '53f90d9a3631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge',
    sa.Column('chg_sys_id', sa.Integer(), nullable=False),
    sa.Column('chg_code', sa.String(), nullable=False),
    sa.Column('chg_desc', sa.String(), nullable=False),
    sa.Column('chg_annual_rate', sa.Float(), nullable=False),
    sa.Column('chg_rate_per', sa.Float(), nullable=False),
    sa.Column('chg_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('chg_sys_id')
    )
    op.create_index(op.f('ix_charge_chg_code'), 'charge', ['chg_code'], unique=False)
    op.create_index(op.f('ix_charge_chg_desc'), 'charge', ['chg_desc'], unique=False)
    op.create_index(op.f('ix_charge_chg_sys_id'), 'charge', ['chg_sys_id'], unique=False)
    op.create_table('condition',
    sa.Column('cond_sys_id', sa.Integer(), nullable=False),
    sa.Column('cond_code', sa.String(), nullable=False),
    sa.Column('cond_desc', sa.String(), nullable=False),
    sa.Column('cond_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cond_sys_id')
    )
    op.create_index(op.f('ix_condition_cond_code'), 'condition', ['cond_code'], unique=False)
    op.create_index(op.f('ix_condition_cond_desc'), 'condition', ['cond_desc'], unique=False)
    op.create_index(op.f('ix_condition_cond_sys_id'), 'condition', ['cond_sys_id'], unique=False)
    op.create_table('cover',
    sa.Column('cvr_sys_id', sa.Integer(), nullable=False),
    sa.Column('cvr_code', sa.String(), nullable=False),
    sa.Column('cvr_desc', sa.String(), nullable=False),
    sa.Column('cvr_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cvr_sys_id')
    )
    op.create_index(op.f('ix_cover_cvr_code'), 'cover', ['cvr_code'], unique=False)
    op.create_index(op.f('ix_cover_cvr_desc'), 'cover', ['cvr_desc'], unique=False)
    op.create_index(op.f('ix_cover_cvr_sys_id'), 'cover', ['cvr_sys_id'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(), nullable=False),
    sa.Column('dept_name', sa.String(), nullable=False),
    sa.Column('dept_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_dept_code'), 'department', ['dept_code'], unique=False)
    op.create_index(op.f('ix_department_dept_name'), 'department', ['dept_name'], unique=False)
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.create_table('division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('divn_comp_code', sa.String(), nullable=False),
    sa.Column('divn_code', sa.String(), nullable=False),
    sa.Column('divn_name', sa.String(), nullable=False),
    sa.Column('divn_short_name', sa.String(), nullable=False),
    sa.Column('divn_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_division_divn_code'), 'division', ['divn_code'], unique=False)
    op.create_index(op.f('ix_division_divn_name'), 'division', ['divn_name'], unique=False)
    op.create_index(op.f('ix_division_divn_short_name'), 'division', ['divn_short_name'], unique=False)
    op.create_index(op.f('ix_division_id'), 'division', ['id'], unique=False)
    op.create_table('section',
    sa.Column('sec_sys_id', sa.Integer(), nullable=False),
    sa.Column('sec_code', sa.String(), nullable=False),
    sa.Column('sec_desc', sa.String(), nullable=False),
    sa.Column('sec_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sec_sys_id')
    )
    op.create_index(op.f('ix_section_sec_code'), 'section', ['sec_code'], unique=False)
    op.create_index(op.f('ix_section_sec_desc'), 'section', ['sec_desc'], unique=False)
    op.create_index(op.f('ix_section_sec_sys_id'), 'section', ['sec_sys_id'], unique=False)
    op.create_table('uwclass',
    sa.Column('class_sys_id', sa.Integer(), nullable=False),
    sa.Column('class_code', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('class_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('class_sys_id')
    )
    op.create_index(op.f('ix_uwclass_class_code'), 'uwclass', ['class_code'], unique=False)
    op.create_index(op.f('ix_uwclass_class_name'), 'uwclass', ['class_name'], unique=False)
    op.create_index(op.f('ix_uwclass_class_sys_id'), 'uwclass', ['class_sys_id'], unique=False)
    op.create_table('product',
    sa.Column('prod_sys_id', sa.Integer(), nullable=False),
    sa.Column('prod_code', sa.String(), nullable=False),
    sa.Column('prod_desc', sa.String(), nullable=False),
    sa.Column('prod_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('prod_class_sys_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_class_sys_id'], ['uwclass.class_sys_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prod_sys_id')
    )
    op.create_index(op.f('ix_product_prod_code'), 'product', ['prod_code'], unique=False)
    op.create_index(op.f('ix_product_prod_desc'), 'product', ['prod_desc'], unique=False)
    op.create_index(op.f('ix_product_prod_sys_id'), 'product', ['prod_sys_id'], unique=False)
    op.create_table('sectioncoverassociation',
    sa.Column('sec_sys_id', sa.Integer(), nullable=False),
    sa.Column('cvr_sys_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cvr_sys_id'], ['cover.cvr_sys_id'], ),
    sa.ForeignKeyConstraint(['sec_sys_id'], ['section.sec_sys_id'], ),
    sa.PrimaryKeyConstraint('sec_sys_id', 'cvr_sys_id')
    )
    op.create_table('productchargeassociation',
    sa.Column('prod_sys_id', sa.Integer(), nullable=False),
    sa.Column('chg_sys_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chg_sys_id'], ['charge.chg_sys_id'], ),
    sa.ForeignKeyConstraint(['prod_sys_id'], ['product.prod_sys_id'], ),
    sa.PrimaryKeyConstraint('prod_sys_id', 'chg_sys_id')
    )
    op.create_table('productconditionassociation',
    sa.Column('prod_sys_id', sa.Integer(), nullable=False),
    sa.Column('cond_sys_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cond_sys_id'], ['condition.cond_sys_id'], ),
    sa.ForeignKeyConstraint(['prod_sys_id'], ['product.prod_sys_id'], ),
    sa.PrimaryKeyConstraint('prod_sys_id', 'cond_sys_id')
    )
    op.create_table('productsectionassociation',
    sa.Column('prod_sys_id', sa.Integer(), nullable=False),
    sa.Column('sec_sys_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_sys_id'], ['product.prod_sys_id'], ),
    sa.ForeignKeyConstraint(['sec_sys_id'], ['section.sec_sys_id'], ),
    sa.PrimaryKeyConstraint('prod_sys_id', 'sec_sys_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productsectionassociation')
    op.drop_table('productconditionassociation')
    op.drop_table('productchargeassociation')
    op.drop_table('sectioncoverassociation')
    op.drop_index(op.f('ix_product_prod_sys_id'), table_name='product')
    op.drop_index(op.f('ix_product_prod_desc'), table_name='product')
    op.drop_index(op.f('ix_product_prod_code'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_uwclass_class_sys_id'), table_name='uwclass')
    op.drop_index(op.f('ix_uwclass_class_name'), table_name='uwclass')
    op.drop_index(op.f('ix_uwclass_class_code'), table_name='uwclass')
    op.drop_table('uwclass')
    op.drop_index(op.f('ix_section_sec_sys_id'), table_name='section')
    op.drop_index(op.f('ix_section_sec_desc'), table_name='section')
    op.drop_index(op.f('ix_section_sec_code'), table_name='section')
    op.drop_table('section')
    op.drop_index(op.f('ix_division_id'), table_name='division')
    op.drop_index(op.f('ix_division_divn_short_name'), table_name='division')
    op.drop_index(op.f('ix_division_divn_name'), table_name='division')
    op.drop_index(op.f('ix_division_divn_code'), table_name='division')
    op.drop_table('division')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_index(op.f('ix_department_dept_name'), table_name='department')
    op.drop_index(op.f('ix_department_dept_code'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_cover_cvr_sys_id'), table_name='cover')
    op.drop_index(op.f('ix_cover_cvr_desc'), table_name='cover')
    op.drop_index(op.f('ix_cover_cvr_code'), table_name='cover')
    op.drop_table('cover')
    op.drop_index(op.f('ix_condition_cond_sys_id'), table_name='condition')
    op.drop_index(op.f('ix_condition_cond_desc'), table_name='condition')
    op.drop_index(op.f('ix_condition_cond_code'), table_name='condition')
    op.drop_table('condition')
    op.drop_index(op.f('ix_charge_chg_sys_id'), table_name='charge')
    op.drop_index(op.f('ix_charge_chg_desc'), table_name='charge')
    op.drop_index(op.f('ix_charge_chg_code'), table_name='charge')
    op.drop_table('charge')
    # ### end Alembic commands ###
