"""installments model

Revision ID: 560487036ed1
Revises: a21cc9bb7dce
Create Date: 2024-10-27 19:06:12.931180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560487036ed1'
down_revision: Union[str, None] = 'a21cc9bb7dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposalpremium',
    sa.Column('prem_sys_id', sa.Integer(), nullable=False),
    sa.Column('prem_sr_no', sa.Integer(), nullable=True),
    sa.Column('prem_tot_amt', sa.Float(), nullable=True),
    sa.Column('prem_curr_code', sa.String(), nullable=True),
    sa.Column('ad_pol_sys_id', sa.Integer(), nullable=True),
    sa.Column('ad_end_no_idx', sa.Integer(), nullable=True),
    sa.Column('ad_pol_no', sa.String(), nullable=True),
    sa.Column('ad_end_no', sa.String(), nullable=True),
    sa.Column('ad_doc_dt', sa.DateTime(), nullable=True),
    sa.Column('ad_tran_code_doc_no', sa.String(), nullable=True),
    sa.Column('ad_premium', sa.Float(), nullable=True),
    sa.Column('ad_stamp_duty', sa.Float(), nullable=True),
    sa.Column('ad_pcf', sa.Float(), nullable=True),
    sa.Column('ad_itl', sa.Float(), nullable=True),
    sa.Column('ad_comesa_fee', sa.Float(), nullable=True),
    sa.Column('ad_road_rescue', sa.Float(), nullable=True),
    sa.Column('ad_commission', sa.Float(), nullable=True),
    sa.Column('ad_wht', sa.Float(), nullable=True),
    sa.Column('prem_prop_sys_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prem_prop_sys_id'], ['proposal.prop_sys_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prem_sys_id')
    )
    op.create_index(op.f('ix_proposalpremium_prem_sys_id'), 'proposalpremium', ['prem_sys_id'], unique=False)
    op.create_table('proposalinstallment',
    sa.Column('inst_sys_id', sa.Integer(), nullable=False),
    sa.Column('inst_sr_no', sa.Integer(), nullable=True),
    sa.Column('inst_curr_code', sa.String(), nullable=True),
    sa.Column('inst_amt', sa.Float(), nullable=True),
    sa.Column('inst_due_dt', sa.DateTime(), nullable=True),
    sa.Column('paymt_mode', sa.String(), nullable=True),
    sa.Column('paymt_ref', sa.String(), nullable=True),
    sa.Column('paymt_amt', sa.Float(), nullable=True),
    sa.Column('paymt_dt', sa.DateTime(), nullable=True),
    sa.Column('rcpt_no', sa.String(), nullable=True),
    sa.Column('rcpt_dt', sa.DateTime(), nullable=True),
    sa.Column('rcpt_amt', sa.Float(), nullable=True),
    sa.Column('inst_prem_sys_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inst_prem_sys_id'], ['proposalpremium.prem_sys_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inst_sys_id')
    )
    op.create_index(op.f('ix_proposalinstallment_inst_sys_id'), 'proposalinstallment', ['inst_sys_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposalinstallment_inst_sys_id'), table_name='proposalinstallment')
    op.drop_table('proposalinstallment')
    op.drop_index(op.f('ix_proposalpremium_prem_sys_id'), table_name='proposalpremium')
    op.drop_table('proposalpremium')
    # ### end Alembic commands ###
