"""track prop_sys_id in premia

Revision ID: 7391d76bd7d6
Revises: 4d9d4f207f72
Create Date: 2024-10-21 16:41:49.781276

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7391d76bd7d6'
down_revision: Union[str, None] = '4d9d4f207f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('pol_prd_sys_id', sa.Integer(), nullable=True))
    op.alter_column('proposalcharge', 'pchg_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalcover', 'prc_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalmotorcert', 'motor_cert_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalmotorcert', 'prai_risk_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalrisk', 'prai_risk_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalsection', 'psec_srno',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalsmi', 'prs_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposalsmi', 'prs_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalsection', 'psec_srno',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalrisk', 'prai_risk_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalmotorcert', 'prai_risk_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalmotorcert', 'motor_cert_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalcover', 'prc_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('proposalcharge', 'pchg_sr_no',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.drop_column('proposal', 'pol_prd_sys_id')
    # ### end Alembic commands ###
