"""external_payload

Revision ID: 99dc177f9c19
Revises: 0b176b23d7c9
Create Date: 2024-09-05 16:29:13.278904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99dc177f9c19'
down_revision: Union[str, None] = '0b176b23d7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('externalpayload',
    sa.Column('ep_sys_id', sa.Integer(), nullable=False),
    sa.Column('external_party', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('notification', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ep_sys_id')
    )
    op.create_index(op.f('ix_externalpayload_ep_sys_id'), 'externalpayload', ['ep_sys_id'], unique=False)
    op.create_index(op.f('ix_externalpayload_external_party'), 'externalpayload', ['external_party'], unique=False)
    op.create_index(op.f('ix_externalpayload_notification'), 'externalpayload', ['notification'], unique=False)
    op.create_index(op.f('ix_externalpayload_transaction_type'), 'externalpayload', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_externalpayload_transaction_type'), table_name='externalpayload')
    op.drop_index(op.f('ix_externalpayload_notification'), table_name='externalpayload')
    op.drop_index(op.f('ix_externalpayload_external_party'), table_name='externalpayload')
    op.drop_index(op.f('ix_externalpayload_ep_sys_id'), table_name='externalpayload')
    op.drop_table('externalpayload')
    # ### end Alembic commands ###
