"""nullable false items

Revision ID: d339fd4e2f69
Revises: a873ac35326d
Create Date: 2023-09-21 09:26:49.694585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d339fd4e2f69"
down_revision: Union[str, None] = "a873ac35326d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("item", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("item", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
