"""Temp Risk master

Revision ID: d8ee2988a10d
Revises: baa0ba22de81
Create Date: 2024-09-25 11:10:22.899178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8ee2988a10d'
down_revision: Union[str, None] = 'baa0ba22de81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t__cover',
    sa.Column('cvr_sys_id', sa.Integer(), nullable=False),
    sa.Column('cvr_code', sa.String(), nullable=False),
    sa.Column('cvr_desc', sa.String(), nullable=False),
    sa.Column('cvr_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cvr_sys_id')
    )
    op.create_index(op.f('ix_t__cover_cvr_code'), 't__cover', ['cvr_code'], unique=False)
    op.create_index(op.f('ix_t__cover_cvr_desc'), 't__cover', ['cvr_desc'], unique=False)
    op.create_index(op.f('ix_t__cover_cvr_sys_id'), 't__cover', ['cvr_sys_id'], unique=False)
    op.create_table('t__risk',
    sa.Column('risk_sys_id', sa.Integer(), nullable=False),
    sa.Column('risk_code', sa.String(), nullable=False),
    sa.Column('risk_desc', sa.String(), nullable=False),
    sa.Column('risk_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('risk_sys_id')
    )
    op.create_index(op.f('ix_t__risk_risk_code'), 't__risk', ['risk_code'], unique=False)
    op.create_index(op.f('ix_t__risk_risk_desc'), 't__risk', ['risk_desc'], unique=False)
    op.create_index(op.f('ix_t__risk_risk_sys_id'), 't__risk', ['risk_sys_id'], unique=False)
    op.create_table('t__section',
    sa.Column('sec_sys_id', sa.Integer(), nullable=False),
    sa.Column('sec_code', sa.String(), nullable=False),
    sa.Column('sec_desc', sa.String(), nullable=False),
    sa.Column('sec_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sec_sys_id')
    )
    op.create_index(op.f('ix_t__section_sec_code'), 't__section', ['sec_code'], unique=False)
    op.create_index(op.f('ix_t__section_sec_desc'), 't__section', ['sec_desc'], unique=False)
    op.create_index(op.f('ix_t__section_sec_sys_id'), 't__section', ['sec_sys_id'], unique=False)
    op.create_table('t__uwclass',
    sa.Column('class_sys_id', sa.Integer(), nullable=False),
    sa.Column('class_code', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('class_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('class_sys_id')
    )
    op.create_index(op.f('ix_t__uwclass_class_code'), 't__uwclass', ['class_code'], unique=False)
    op.create_index(op.f('ix_t__uwclass_class_name'), 't__uwclass', ['class_name'], unique=False)
    op.create_index(op.f('ix_t__uwclass_class_sys_id'), 't__uwclass', ['class_sys_id'], unique=False)
    op.create_table('t__product',
    sa.Column('prod_sys_id', sa.Integer(), nullable=False),
    sa.Column('prod_code', sa.String(), nullable=False),
    sa.Column('prod_desc', sa.String(), nullable=False),
    sa.Column('prod_frz_flag', sa.Boolean(), nullable=False),
    sa.Column('pol_trans_dflt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prod_class_sys_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_class_sys_id'], ['t__uwclass.class_sys_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prod_sys_id')
    )
    op.create_index(op.f('ix_t__product_prod_code'), 't__product', ['prod_code'], unique=False)
    op.create_index(op.f('ix_t__product_prod_desc'), 't__product', ['prod_desc'], unique=False)
    op.create_index(op.f('ix_t__product_prod_sys_id'), 't__product', ['prod_sys_id'], unique=False)
    op.create_table('t__riskcoverassociation',
    sa.Column('risk_sys_id', sa.Integer(), nullable=False),
    sa.Column('cvr_sys_id', sa.Integer(), nullable=False),
    sa.Column('cvr_trans_dflt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cvr_sys_id'], ['t__cover.cvr_sys_id'], ),
    sa.ForeignKeyConstraint(['risk_sys_id'], ['t__risk.risk_sys_id'], ),
    sa.PrimaryKeyConstraint('risk_sys_id', 'cvr_sys_id')
    )
    op.create_table('t__sectionriskassociation',
    sa.Column('sec_sys_id', sa.Integer(), nullable=False),
    sa.Column('risk_sys_id', sa.Integer(), nullable=False),
    sa.Column('risk_trans_dflt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['risk_sys_id'], ['t__risk.risk_sys_id'], ),
    sa.ForeignKeyConstraint(['sec_sys_id'], ['t__section.sec_sys_id'], ),
    sa.PrimaryKeyConstraint('sec_sys_id', 'risk_sys_id')
    )
    op.create_table('t__productsectionassociation',
    sa.Column('prod_sys_id', sa.Integer(), nullable=False),
    sa.Column('sec_sys_id', sa.Integer(), nullable=False),
    sa.Column('sec_trans_dflt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_sys_id'], ['t__product.prod_sys_id'], ),
    sa.ForeignKeyConstraint(['sec_sys_id'], ['t__section.sec_sys_id'], ),
    sa.PrimaryKeyConstraint('prod_sys_id', 'sec_sys_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t__productsectionassociation')
    op.drop_table('t__sectionriskassociation')
    op.drop_table('t__riskcoverassociation')
    op.drop_index(op.f('ix_t__product_prod_sys_id'), table_name='t__product')
    op.drop_index(op.f('ix_t__product_prod_desc'), table_name='t__product')
    op.drop_index(op.f('ix_t__product_prod_code'), table_name='t__product')
    op.drop_table('t__product')
    op.drop_index(op.f('ix_t__uwclass_class_sys_id'), table_name='t__uwclass')
    op.drop_index(op.f('ix_t__uwclass_class_name'), table_name='t__uwclass')
    op.drop_index(op.f('ix_t__uwclass_class_code'), table_name='t__uwclass')
    op.drop_table('t__uwclass')
    op.drop_index(op.f('ix_t__section_sec_sys_id'), table_name='t__section')
    op.drop_index(op.f('ix_t__section_sec_desc'), table_name='t__section')
    op.drop_index(op.f('ix_t__section_sec_code'), table_name='t__section')
    op.drop_table('t__section')
    op.drop_index(op.f('ix_t__risk_risk_sys_id'), table_name='t__risk')
    op.drop_index(op.f('ix_t__risk_risk_desc'), table_name='t__risk')
    op.drop_index(op.f('ix_t__risk_risk_code'), table_name='t__risk')
    op.drop_table('t__risk')
    op.drop_index(op.f('ix_t__cover_cvr_sys_id'), table_name='t__cover')
    op.drop_index(op.f('ix_t__cover_cvr_desc'), table_name='t__cover')
    op.drop_index(op.f('ix_t__cover_cvr_code'), table_name='t__cover')
    op.drop_table('t__cover')
    # ### end Alembic commands ###
