"""create_update stamp defaults

Revision ID: f74f011e3b71
Revises: d339fd4e2f69
Create Date: 2023-09-23 11:28:11.098931

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f74f011e3b71"
down_revision: Union[str, None] = "d339fd4e2f69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column("item", sa.Column("created_by", sa.String(length=30), nullable=True))
    op.add_column(
        "item",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column("item", sa.Column("updated_by", sa.String(length=30), nullable=True))
    op.add_column(
        "person",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "person", sa.Column("created_by", sa.String(length=30), nullable=True)
    )
    op.add_column(
        "person",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "person", sa.Column("updated_by", sa.String(length=30), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("person", "updated_by")
    op.drop_column("person", "updated_at")
    op.drop_column("person", "created_by")
    op.drop_column("person", "created_at")
    op.drop_column("item", "updated_by")
    op.drop_column("item", "updated_at")
    op.drop_column("item", "created_by")
    op.drop_column("item", "created_at")
    # ### end Alembic commands ###
