name: Trigger auto deployment for jazk-api-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ uat_branch ]
    paths:
    - '**'
    - '.github/workflows/jazk-api-app-AutoDeployTrigger-280f1a53-6001-415b-a83e-38c5a297364f.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.JAZKAPIAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          # appSourcePath: ${{ github.workspace }} 
          appSourcePath: ${{ github.workspace }}/jaz_api_v03 
          registryUrl: jazkapiregistry.azurecr.io
          registryUsername: ${{ secrets.JAZKAPIAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JAZKAPIAPP_REGISTRY_PASSWORD }}
          containerAppName: jazk-api-app
          resourceGroup: jazk-api-rg
          containerAppEnvironment: jazk-api-env
          ingress: external
          targetPort: 3100
          dockerfilePath: Dockerfile
          # imageToBuild: jazkapiregistry.azurecr.io/jazk-api-app:${{ github.sha }}
          imageToBuild: jazkapiregistry.azurecr.io/jaz_api_v03:latest
