name: Trigger auto deployment for jazk-api-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ uat_branch ]
    paths:
    - 'Dockerfile.Azure/**'
    - '.github/workflows/jazk-api-app-AutoDeployTrigger-d1c9c379-2953-43bb-a034-b2a25a4a98a6.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.JAZKAPIAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Dockerfile.Azure 
          registryUrl: jazkapiregistry.azurecr.io
          registryUsername: ${{ secrets.JAZKAPIAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JAZKAPIAPP_REGISTRY_PASSWORD }}
          containerAppName: jazk-api-app
          resourceGroup: jazk-api-rg
          imageToBuild: jazkapiregistry.azurecr.io/jaz_api_v03:${{ github.sha }}
          dockerfilePath: Dockerfile

     

